### ISSUE TITLE
 ValueError: --do_eval requires a validation dataset

### ISSUE THREAD

**Issue by 10637409100** [yyDing1/GNER#9]
12/10/2024 12:37:18 - INFO - datasets.arrow_dataset - Concatenating 4 shards
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/fu/下载/GNER-main/GNER-main/src/run.py", line 507, in <module>
[rank0]:     main()
[rank0]:   File "/home/fu/下载/GNER-main/GNER-main/src/run.py", line 370, in main
[rank0]:     raise ValueError("--do_eval requires a validation dataset")
[rank0]: ValueError: --do_eval requires a validation dataset
There is an error about missing a validation set, but there is no content about the validation set in the given data.

**Comment by 10637409100** [comment]
I initially solved this problem because the 'valid' on line 369 of run.py was changed to 'validation'
